/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.LoginController;
import Modelo.LoginM;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(485, 295);
        this.setLocationRelativeTo(null);
        
               
    }
    
    LoginController m = new LoginController();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contralog = new javax.swing.JTextField();
        nombrelog = new javax.swing.JTextField();
        acceder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(0, 0, 400, 269));
        setResizable(false);
        getContentPane().setLayout(null);

        contralog.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        contralog.setForeground(new java.awt.Color(0, 0, 255));
        contralog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contralog.setText("Contraseña");
        contralog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contralogMouseClicked(evt);
            }
        });
        getContentPane().add(contralog);
        contralog.setBounds(170, 200, 140, 22);

        nombrelog.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nombrelog.setForeground(new java.awt.Color(0, 0, 204));
        nombrelog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombrelog.setText("Nombre");
        nombrelog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombrelogMouseClicked(evt);
            }
        });
        getContentPane().add(nombrelog);
        nombrelog.setBounds(170, 170, 140, 22);

        acceder.setText("INGRESAR");
        acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederActionPerformed(evt);
            }
        });
        getContentPane().add(acceder);
        acceder.setBounds(190, 230, 90, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Helados.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrelogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrelogMouseClicked
        nombrelog.setText("");
    }//GEN-LAST:event_nombrelogMouseClicked

    private void contralogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contralogMouseClicked
        contralog.setText("");
    }//GEN-LAST:event_contralogMouseClicked

    private void accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederActionPerformed
        LoginM log = new LoginM();
        m.generarInicio();
        LoginController.guardarUsuarios();
        String z = nombrelog.getText();
        if (LoginController.consultar(z).equals(z)){
            JOptionPane.showMessageDialog(null, "Login Funcionando");
        }else{
            JOptionPane.showMessageDialog(null, "Login Fallando");
        }
    }//GEN-LAST:event_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceder;
    private javax.swing.JTextField contralog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombrelog;
    // End of variables declaration//GEN-END:variables
}
